import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-procurement-contract-price-compliance-recovery",
  "engine": "recovery",
  "title": "Procurement Contract Price Compliance Recovery",
  "shortTitle": "Supplier Price Recovery",
  "tagline": "Enforce negotiated prices, discounts, rebates, freight terms, and supplier commitments",
  "industry": "Procurement Financial Assurance",
  "uiPort": 4573,
  "apiPort": 5573,
  "accent": "#0f766e",
  "currency": "USD",
  "primaryOutcome": "Supplier overbilling and missed commercial entitlements converted into debit memos, credits, and prevented leakage",
  "valueNarrative": "Reconcile contracts, catalogs, purchase orders, receipts, invoices, indexes, rebates, and credits at line-item precision.",
  "calculation": {
    "actualKey": "invoicedAmount",
    "expectedKey": "contractAmount",
    "actualLabel": "Supplier Invoiced Amount",
    "expectedLabel": "Contract-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Contract pricing, purchasing, receipt, and invoice evidence indicate supplier overbilling or missed entitlement.",
    "actions": [
      "Validate the governing agreement and effective rules",
      "Reconcile transaction-level source evidence",
      "Prepare and submit the recovery or correction package",
      "Track response and reconcile realized financial outcome"
    ]
  }
},[
feature("supplier-contract-library","SPR01","Supplier contract library","Reconcile supplier contract library using supplier agreements, catalogs, purchase orders, receipts, invoices, price indexes, freight terms, rebate schedules, and credits.","Produce a governed supplier contract library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierContract","Supplier / Contract","text","Northstar Industrial / MSA-2026-18"],["caseReference","Supplier contract library Reference","text","SPR01-2026-001"],["invoicedAmount","Supplier Invoiced Amount","currency",1280000],["contractAmount","Contract-Supported Amount","currency",1135000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"invoicedAmount",subjects:["Direct materials supplier","Facilities services contract","Packaging supplier","MRO category","Professional services agreement"]}),
feature("sku-and-service-catalog","SPR02","SKU and service catalog","Reconcile sku and service catalog using supplier agreements, catalogs, purchase orders, receipts, invoices, price indexes, freight terms, rebate schedules, and credits.","Produce a governed sku and service catalog decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierContract","Supplier / Contract","text","Northstar Industrial / MSA-2026-18"],["caseReference","SKU and service catalog Reference","text","SPR02-2026-001"],["invoicedAmount","Supplier Invoiced Amount","currency",1280000],["contractAmount","Contract-Supported Amount","currency",1135000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"invoicedAmount",subjects:["Direct materials supplier","Facilities services contract","Packaging supplier","MRO category","Professional services agreement"]}),
feature("purchase-order-ingestion","SPR03","Purchase-order ingestion","Reconcile purchase-order ingestion using supplier agreements, catalogs, purchase orders, receipts, invoices, price indexes, freight terms, rebate schedules, and credits.","Produce a governed purchase-order ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierContract","Supplier / Contract","text","Northstar Industrial / MSA-2026-18"],["caseReference","Purchase-order ingestion Reference","text","SPR03-2026-001"],["invoicedAmount","Supplier Invoiced Amount","currency",1280000],["contractAmount","Contract-Supported Amount","currency",1135000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"invoicedAmount",subjects:["Direct materials supplier","Facilities services contract","Packaging supplier","MRO category","Professional services agreement"]}),
feature("invoice-ingestion","SPR04","Invoice ingestion","Reconcile invoice ingestion using supplier agreements, catalogs, purchase orders, receipts, invoices, price indexes, freight terms, rebate schedules, and credits.","Produce a governed invoice ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierContract","Supplier / Contract","text","Northstar Industrial / MSA-2026-18"],["caseReference","Invoice ingestion Reference","text","SPR04-2026-001"],["invoicedAmount","Supplier Invoiced Amount","currency",1280000],["contractAmount","Contract-Supported Amount","currency",1135000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"invoicedAmount",subjects:["Direct materials supplier","Facilities services contract","Packaging supplier","MRO category","Professional services agreement"]}),
feature("contract-price-reconstruction","SPR05","Contract-price reconstruction","Reconcile contract-price reconstruction using supplier agreements, catalogs, purchase orders, receipts, invoices, price indexes, freight terms, rebate schedules, and credits.","Produce a governed contract-price reconstruction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierContract","Supplier / Contract","text","Northstar Industrial / MSA-2026-18"],["caseReference","Contract-price reconstruction Reference","text","SPR05-2026-001"],["invoicedAmount","Supplier Invoiced Amount","currency",1280000],["contractAmount","Contract-Supported Amount","currency",1135000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"invoicedAmount",subjects:["Direct materials supplier","Facilities services contract","Packaging supplier","MRO category","Professional services agreement"]}),
feature("volume-discount-validation","SPR06","Volume discount validation","Reconcile volume discount validation using supplier agreements, catalogs, purchase orders, receipts, invoices, price indexes, freight terms, rebate schedules, and credits.","Produce a governed volume discount validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierContract","Supplier / Contract","text","Northstar Industrial / MSA-2026-18"],["caseReference","Volume discount validation Reference","text","SPR06-2026-001"],["invoicedAmount","Supplier Invoiced Amount","currency",1280000],["contractAmount","Contract-Supported Amount","currency",1135000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"invoicedAmount",subjects:["Direct materials supplier","Facilities services contract","Packaging supplier","MRO category","Professional services agreement"]}),
feature("index-escalation-verification","SPR07","Index escalation verification","Reconcile index escalation verification using supplier agreements, catalogs, purchase orders, receipts, invoices, price indexes, freight terms, rebate schedules, and credits.","Produce a governed index escalation verification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierContract","Supplier / Contract","text","Northstar Industrial / MSA-2026-18"],["caseReference","Index escalation verification Reference","text","SPR07-2026-001"],["invoicedAmount","Supplier Invoiced Amount","currency",1280000],["contractAmount","Contract-Supported Amount","currency",1135000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"invoicedAmount",subjects:["Direct materials supplier","Facilities services contract","Packaging supplier","MRO category","Professional services agreement"]}),
feature("most-favored-pricing-control","SPR08","Most-favored-pricing control","Reconcile most-favored-pricing control using supplier agreements, catalogs, purchase orders, receipts, invoices, price indexes, freight terms, rebate schedules, and credits.","Produce a governed most-favored-pricing control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierContract","Supplier / Contract","text","Northstar Industrial / MSA-2026-18"],["caseReference","Most-favored-pricing control Reference","text","SPR08-2026-001"],["invoicedAmount","Supplier Invoiced Amount","currency",1280000],["contractAmount","Contract-Supported Amount","currency",1135000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"invoicedAmount",subjects:["Direct materials supplier","Facilities services contract","Packaging supplier","MRO category","Professional services agreement"]}),
feature("freight-term-validation","SPR09","Freight-term validation","Reconcile freight-term validation using supplier agreements, catalogs, purchase orders, receipts, invoices, price indexes, freight terms, rebate schedules, and credits.","Produce a governed freight-term validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierContract","Supplier / Contract","text","Northstar Industrial / MSA-2026-18"],["caseReference","Freight-term validation Reference","text","SPR09-2026-001"],["invoicedAmount","Supplier Invoiced Amount","currency",1280000],["contractAmount","Contract-Supported Amount","currency",1135000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"invoicedAmount",subjects:["Direct materials supplier","Facilities services contract","Packaging supplier","MRO category","Professional services agreement"]}),
feature("surcharge-audit","SPR10","Surcharge audit","Reconcile surcharge audit using supplier agreements, catalogs, purchase orders, receipts, invoices, price indexes, freight terms, rebate schedules, and credits.","Produce a governed surcharge audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierContract","Supplier / Contract","text","Northstar Industrial / MSA-2026-18"],["caseReference","Surcharge audit Reference","text","SPR10-2026-001"],["invoicedAmount","Supplier Invoiced Amount","currency",1280000],["contractAmount","Contract-Supported Amount","currency",1135000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"invoicedAmount",subjects:["Direct materials supplier","Facilities services contract","Packaging supplier","MRO category","Professional services agreement"]}),
feature("duplicate-and-split-order-detection","SPR11","Duplicate and split-order detection","Reconcile duplicate and split-order detection using supplier agreements, catalogs, purchase orders, receipts, invoices, price indexes, freight terms, rebate schedules, and credits.","Produce a governed duplicate and split-order detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierContract","Supplier / Contract","text","Northstar Industrial / MSA-2026-18"],["caseReference","Duplicate and split-order detection Reference","text","SPR11-2026-001"],["invoicedAmount","Supplier Invoiced Amount","currency",1280000],["contractAmount","Contract-Supported Amount","currency",1135000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"invoicedAmount",subjects:["Direct materials supplier","Facilities services contract","Packaging supplier","MRO category","Professional services agreement"]}),
feature("rebate-accrual-calculation","SPR12","Rebate accrual calculation","Reconcile rebate accrual calculation using supplier agreements, catalogs, purchase orders, receipts, invoices, price indexes, freight terms, rebate schedules, and credits.","Produce a governed rebate accrual calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierContract","Supplier / Contract","text","Northstar Industrial / MSA-2026-18"],["caseReference","Rebate accrual calculation Reference","text","SPR12-2026-001"],["invoicedAmount","Supplier Invoiced Amount","currency",1280000],["contractAmount","Contract-Supported Amount","currency",1135000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"invoicedAmount",subjects:["Direct materials supplier","Facilities services contract","Packaging supplier","MRO category","Professional services agreement"]}),
feature("supplier-exception-workbench","SPR13","Supplier exception workbench","Reconcile supplier exception workbench using supplier agreements, catalogs, purchase orders, receipts, invoices, price indexes, freight terms, rebate schedules, and credits.","Produce a governed supplier exception workbench decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierContract","Supplier / Contract","text","Northstar Industrial / MSA-2026-18"],["caseReference","Supplier exception workbench Reference","text","SPR13-2026-001"],["invoicedAmount","Supplier Invoiced Amount","currency",1280000],["contractAmount","Contract-Supported Amount","currency",1135000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"invoicedAmount",subjects:["Direct materials supplier","Facilities services contract","Packaging supplier","MRO category","Professional services agreement"]}),
feature("debit-memo-generation","SPR14","Debit memo generation","Reconcile debit memo generation using supplier agreements, catalogs, purchase orders, receipts, invoices, price indexes, freight terms, rebate schedules, and credits.","Produce a governed debit memo generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierContract","Supplier / Contract","text","Northstar Industrial / MSA-2026-18"],["caseReference","Debit memo generation Reference","text","SPR14-2026-001"],["invoicedAmount","Supplier Invoiced Amount","currency",1280000],["contractAmount","Contract-Supported Amount","currency",1135000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"invoicedAmount",subjects:["Direct materials supplier","Facilities services contract","Packaging supplier","MRO category","Professional services agreement"]}),
feature("credit-reconciliation","SPR15","Credit reconciliation","Reconcile credit reconciliation using supplier agreements, catalogs, purchase orders, receipts, invoices, price indexes, freight terms, rebate schedules, and credits.","Produce a governed credit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierContract","Supplier / Contract","text","Northstar Industrial / MSA-2026-18"],["caseReference","Credit reconciliation Reference","text","SPR15-2026-001"],["invoicedAmount","Supplier Invoiced Amount","currency",1280000],["contractAmount","Contract-Supported Amount","currency",1135000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"invoicedAmount",subjects:["Direct materials supplier","Facilities services contract","Packaging supplier","MRO category","Professional services agreement"]}),
feature("supplier-and-category-leakage-analytics","SPR16","Supplier and category leakage analytics","Reconcile supplier and category leakage analytics using supplier agreements, catalogs, purchase orders, receipts, invoices, price indexes, freight terms, rebate schedules, and credits.","Produce a governed supplier and category leakage analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierContract","Supplier / Contract","text","Northstar Industrial / MSA-2026-18"],["caseReference","Supplier and category leakage analytics Reference","text","SPR16-2026-001"],["invoicedAmount","Supplier Invoiced Amount","currency",1280000],["contractAmount","Contract-Supported Amount","currency",1135000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"invoicedAmount",subjects:["Direct materials supplier","Facilities services contract","Packaging supplier","MRO category","Professional services agreement"]})
]);
